AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'data/**/*'
    - 'libs/tmux-plugins/**/*'
    - 'libs/z/**/*'
    - 'oh-my-zsh/custom/plugins/zsh-autosuggestions/**/*'
    - 'oh-my-zsh/custom/plugins/zsh-syntax-highlighting/**/*'

Metrics/MethodLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
