#!/usr/bin/env bash
# shellcheck disable=2154

# Git Prompt (enhanced prompt with Git repo info).

# -- See if the Homebrew package is installed.
__GIT_PROMPT_DIR="$(brew --prefix bash-git-prompt)/share/"

if [ -f "$__GIT_PROMPT_DIR/gitprompt.sh" ]; then

	# If so, export custom configuration.
	export __GIT_PROMPT_DIR
	export GIT_PROMPT_ONLY_IN_REPO=0
	export GIT_PROMPT_THEME=Default
	export GIT_PROMPT_COMMAND_OK="${ANSI_GREEN}✔${ANSI_RESET}"
	export GIT_PROMPT_COMMAND_FAIL="${ANSI_RED}✘:_LAST_COMMAND_STATE_${ANSI_RESET}"
	export GIT_PROMPT_START_USER="_LAST_COMMAND_INDICATOR_ ${ANSI_YELLOW}\W${ANSI_RESET}"
	export GIT_PROMPT_END_USER=" $ "

	# shellcheck source=/dev/null
	source "$__GIT_PROMPT_DIR/gitprompt.sh"

fi
