#!/usr/bin/env bash

if [ -d "$(brew --prefix ndenv)" ]; then
  # Contains Node versions, ndenv plugins, etc.
  export NDENV_ROOT
  NDENV_ROOT="$(brew --prefix ndenv)"

  # Initialize ndenv.
  eval "$(ndenv init -)"

  # Set global version if one isn't already set.
  if [ -z "$(ndenv global)" ]; then
    ndenv global 8.8.1
  fi
fi
