#!/usr/bin/env bash

if [ -d "$(brew --prefix rbenv)" ]; then
  # Contains Ruby versions and shims.
  export RBENV_ROOT="$(brew --prefix rbenv)"

  # The default Ruby version.
  export RBENV_VERSION="2.3.1"

  # Initialize rbenv.
  eval "$(rbenv init -)"
fi
