#!/usr/bin/env bash
# shellcheck disable=1090

RVM_DIR="$HOME/.rvm"
export RVM_DIR

if [ ! -d "$RVM_DIR" ]; then
  gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  curl -sSL https://get.rvm.io | bash -s stable
fi

source "$RVM_DIR/scripts/rvm"
